name: Deploy to VPS

on:
  push:
    branches:
      - main  # Pas dit aan naar 'master' als jouw standaard branch zo heet

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script: |
            cd /opt/wk-poule
            git pull
            npm install --production
            pm2 restart wk-poule || pm2 start server.js --name "wk-poule"
